packageExtensions:
  jest-config@^27.5.1:
    dependencies:
      jest-runtime: ^27.5.1

  # Waiting for https://github.com/facebook/jest/issues/12366
  "@cspotcode/source-map-support@*":
    dependencies:
      source-map-support: "*"

  # react-inspector@npm:5.1.1 doesn't allow React 18, but let's assume it works
  # and see if it breaks.
  # "react-inspector@5.1.1":
  #   peerDependencies:
  #     react: "^16.8.0 || ^17.0.0 || ^18.0.0"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: "@yarnpkg/plugin-typescript"
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"

yarnPath: .yarn/releases/yarn-3.2.0.cjs
