packageExtensions:
  jest-config@^27.5.1:
    dependencies:
      jest-runtime: ^27.5.1

  # Waiting for https://github.com/facebook/jest/issues/12366
  "@cspotcode/source-map-support@*":
    dependencies:
      source-map-support: "*"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: "@yarnpkg/plugin-typescript"

yarnPath: .yarn/releases/yarn-3.2.0.cjs
